name: Release to dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: Cere-IO/reusable-workflows/.github/workflows/build-and-upload-static.yaml@master
    with:
      runs-on: '["self-hosted", "cere-io-large"]'
      build_container: 'node:14-buster'
      deploy_container: 'ubuntu:20.04'
      install_packages_command: 'npm ci'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'build'
    secrets:
      NETWORK_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_CORE_AWS_ACCESS_KEY_ID }}
      NETWORK_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_CORE_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID_DEV }}
